version: '3.8'

services:
  apache-php:
    build: .
    container_name: api-php
    volumes:
      - ./public:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./src:/var/www/html/src
      - ./.env:/var/www/html/.env
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - rede

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - rede

volumes:
  db_data:

networks:
  rede:
