version: '3.8'

services:
  apache-php:
    build: .
    # image: php:8.2-apache
    container_name: api-php
    volumes:
      - ./api:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - rede

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - rede

volumes:
  db_data:

networks:
  rede:
